version: '3.9'

services:
  bot:
    container_name: bot
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8005:8005"
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./core/.env
    volumes:
      - .:/code
    networks:
      - time_management_network

networks:
  time_management_network:
    external: Trued